.TH "Reference k adresáři src/safarik_hurricane" 3 "čt 14. kvě 2020" "Version Final" "Hurricanes_Documentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reference k adresáři src/safarik_hurricane
.SH SYNOPSIS
.br
.PP
.SS "Soubory"

.in +1c
.ti -1c
.RI "soubor \fBComparatorBySpeed\&.java\fP"
.br
.ti -1c
.RI "soubor \fBHurricane\&.java\fP"
.br
.ti -1c
.RI "soubor \fBHurricanesData\&.java\fP"
.br
.ti -1c
.RI "soubor \fBMain_Hurricane\&.java\fP"
.br
.in -1c
