.TH "src/safarik_hurricane/ComparatorBySpeed.java" 3 "čt 14. kvě 2020" "Version Final" "Hurricanes_Documentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/safarik_hurricane/ComparatorBySpeed.java
.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBsafarik_hurricane\&.ComparatorBySpeed\fP"
.br
.in -1c
.SS "Balíky"

.in +1c
.ti -1c
.RI "package \fBsafarik_hurricane\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Hurricanes_Documentations\&.
