.TH "safarik_hurricane" 3 "čt 14. kvě 2020" "Version Final" "Hurricanes_Documentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
safarik_hurricane
.SH SYNOPSIS
.br
.PP
.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBComparatorBySpeed\fP"
.br
.ti -1c
.RI "class \fBHurricane\fP"
.br
.ti -1c
.RI "class \fBHurricanesData\fP"
.br
.ti -1c
.RI "class \fBMain_Hurricane\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Hurricanes_Documentations\&.
