.TH "safarik_hurricane.Main_Hurricane" 3 "čt 14. kvě 2020" "Version Final" "Hurricanes_Documentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
safarik_hurricane.Main_Hurricane
.SH SYNOPSIS
.br
.PP
.SS "Statické veřejné metody"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SS "Statické veřejné atributy"

.in +1c
.ti -1c
.RI "static Scanner \fBsc\fP = new Scanner(System\&.in)"
.br
.in -1c
.SS "Statické privátní metody"

.in +1c
.ti -1c
.RI "static String \fBgetMenu\fP ()"
.br
.RI "Gives the options menu for user choice\&. "
.in -1c
.SH "Detailní popis"
.PP 

.PP
\fBAutor\fP
.RS 4
David 
.RE
.PP

.PP
Definice je uvedena na řádku 12 v souboru Main_Hurricane\&.java\&.
.SH "Dokumentace k metodám"
.PP 
.SS "static String safarik_hurricane\&.Main_Hurricane\&.getMenu ()\fC [static]\fP, \fC [private]\fP"

.PP
Gives the options menu for user choice\&. 
.PP
\fBNávratová hodnota\fP
.RS 4
String with possible choice options 
.RE
.PP

.PP
Definice je uvedena na řádku 63 v souboru Main_Hurricane\&.java\&.
.SS "static void safarik_hurricane\&.Main_Hurricane\&.main (String[] args)\fC [static]\fP"

.PP
\fBParametry\fP
.RS 4
\fIargs\fP the command line arguments 
.RE
.PP

.PP
Definice je uvedena na řádku 18 v souboru Main_Hurricane\&.java\&.
.SH "Dokumentace k datovým členům"
.PP 
.SS "Scanner safarik_hurricane\&.Main_Hurricane\&.sc = new Scanner(System\&.in)\fC [static]\fP"

.PP
Definice je uvedena na řádku 13 v souboru Main_Hurricane\&.java\&.

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Hurricanes_Documentations\&.
