.TH "safarik_hurricane.ComparatorBySpeed" 3 "čt 14. kvě 2020" "Version Final" "Hurricanes_Documentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
safarik_hurricane.ComparatorBySpeed
.SH SYNOPSIS
.br
.PP
.PP
Dědí z bázové třídy Comparator< Hurricane >\&.
.SS "Veřejné metody"

.in +1c
.ti -1c
.RI "int \fBcompare\fP (\fBHurricane\fP o1, \fBHurricane\fP o2)"
.br
.in -1c
.SH "Detailní popis"
.PP 

.PP
\fBAutor\fP
.RS 4
David 
.RE
.PP

.PP
Definice je uvedena na řádku 9 v souboru ComparatorBySpeed\&.java\&.
.SH "Dokumentace k metodám"
.PP 
.SS "int safarik_hurricane\&.ComparatorBySpeed\&.compare (\fBHurricane\fP o1, \fBHurricane\fP o2)"

.PP
Definice je uvedena na řádku 12 v souboru ComparatorBySpeed\&.java\&.

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu Hurricanes_Documentations\&.
